on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "18.0"
  push:
    branches:
      - "18.0"

permissions: write-all

jobs:
  run:
    runs-on: ubuntu-latest

    env:
    #  GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    #- name: Authenticate GitHub CLI
    #  run: |
    #    echo "GH_TOKEN=$GH_TOKEN"
    #    gh auth login --with-token <<< "$GH_TOKEN"

    - name: Assign reviewer
      env:
        #REVIEWER: "eldy,lvessiller-opendsi,rycks" # Remplacez par le nom d'utilisateur GitHub du reviewer
        REVIEWER: "rycks" # Remplacez par le nom d'utilisateur GitHub du reviewer
      run: |
        echo "GH_TOKEN=$GH_TOKEN"
        pr_number=$(jq --raw-output .number < $GITHUB_EVENT_PATH)
        gh pr edit $pr_number --add-reviewer "$REVIEWER"
      continue-on-error: true
