on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "18.0"
  push:
    branches:
      - "18.0"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: gh auth login --with-token <<< "$GH_TOKEN"

    - name: Assign reviewer
      env:
        #REVIEWER: "eldy,lvessiller-opendsi,rycks" # Remplacez par le nom d'utilisateur GitHub du reviewer
        REVIEWER: "rycks" # Remplacez par le nom d'utilisateur GitHub du reviewer
      run: |
        pr_number=$(jq --raw-output .number < $GITHUB_EVENT_PATH)
        gh pr edit $pr_number --add-reviewer "$REVIEWER"
