on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "18.0"

permissions: write-all

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo "variable org: ${{vars.AAA}}"
          echo "env prg: ${{env.AAA}}"
          echo "secret org: ${{secrets.BBB}}"
          echo "variable repository of orga: ${{vars.CCC}}"
